stages:
load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
       - src/get_data.py
       - src/load_data.py
       - Source_Code/penguin_course5i.csv
    outs:
       - data/raw/penguin_course5i.csv

split_data:
      cmd: python src/split_data.py --config=params.yaml
      deps:
        - src/split_data.py
        - data/raw/penguin_course5i.csv
      outs:
        - data/processed/train_penguin_course5i.csv
        - data/processed/test_penguin_course5i.csv

train_and_evaluate:
        cmd: python src/train_and_evaluate.py --config=params.yaml
        deps: 
          - data/Processed/train_penguin_course5i.csv
          - data/Processed/test_penguin_course5i.csv
          - src/train_and_evaluate.py

       Params:
          - estimators.DecissionTree.Params.criterion
          - estimators.DecissionTree.Params.splitter
          - estimators.DecissionTree.Params.max_depth
          - estimators.DecissionTree.Params.min_samples_leaf

       metrics:
          - reports/Scores.json
          cache: false
          - reports/Params.json
          cache: false

       outs:
         -models/model.joblib
