base:
  project: mlops-penguin
  random_state: 42
  target_col: species

data_source:
  s3_source: source_code/penguin_course5i.csv

load_data:
  raw_dataset_csv: data/raw/penguin_course5i.csv

split_data:
  train_path: data/processed/train_penguin_course5i.csv
  test_path: data/processed/test_penguin_course5i.csv
  test_size: 0.2

estimators:
  DecissionTree:
    params:
      criterion: 'gini'
      splitter: 'best'
      max_depth: 3
      min_samples_leaf: 5

model_dir: models

reports :
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

